version: '1'

services:

  tracker:
    image: multimoml/tracker:latest
    container_name: tracker
    restart: unless-stopped
    networks:
      - products-db
      - traefik-proxy

    environment:

      # MongoDB
      M_USERNAME: ${M_USERNAME}
      M_PASSWORD: ${M_PASSWORD}
      DATABASE: ${DATABASE}

      # tracker
      ENVIRONMENT: "prod"
      M_SERVER: products-db:27017
      RUN_INTERVAL: 14400 # 4h in seconds
      PORT: 6003
    labels:
      traefik.enable: true
      traefik.docker.network: traefik-proxy # needed if you have multiple networks and no default
      traefik.http.routers.tracker.rule: Host(`${DOMAIN}`) && PathPrefix(`/new/`)
      traefik.http.routers.tracker.entrypoints: https
      traefik.http.services.tracker.loadbalancer.server.port: 6003

networks:
  products-db:
    external: true
  traefik-proxy:
    external: true
